name: Build Pull request
on:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}
  TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
  NEXT_PUBLIC_TINA_BRANCH: ${{ github.head_ref }}
  SRH_TOKEN: example_token

jobs:
  container-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18", "20"]
    name: Node ${{ matrix.node }} sample
    container: denoland/deno
    services:
      redis:
        image: redis/redis-stack-server:6.2.6-v6 # 6.2 is the Upstash compatible Redis version
      srh:
        image: hiett/serverless-redis-http:latest
        env:
          SRH_MODE: env # We are using env mode because we are only connecting to one server.
          SRH_TOKEN: ${{ env.SRH_TOKEN }}
          SRH_CONNECTION_STRING: redis://redis:6379

    steps:
      - name: install git
        run: apt-get update && apt-get install -y git

      - uses: actions/checkout@v3
        name: Checkout

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - run: npm install -g yarn && yarn install
        name: install

      - run: yarn build
        name: build
        env:
          GITHUB_BRANCH: ${{ github.head_ref }}
          KV_REST_API_URL: http://srh:80
          KV_REST_API_TOKEN: ${{ env.SRH_TOKEN }}
